### ISSUE TITLE
Example

### ISSUE THREAD

**Issue by mstumberger** [brycedarling/redux-autobahn-js#1]
Hello,

I was just looking for something like this!

Is there a possibility to get some example of usage or maybe even a demo project of a simple RPC call and maybe a subscription since I'm new to react and redux?

Regards,
Marko

**Comment by brycedarling** [comment]
Hey Marko, I took a stab at putting together an example with this using the Poloniex push API (which is what I originally built this for). I got connect and subscribe calls working, but no events coming through... and I am not sure if it's something on my end or if the Poloniex push API isn't pushing events.. hmm.

If you'd like, I can still push that up, I am just not sure if it's my busted library or not that is causing this and I don't have more time to investigate right now :)

You might want to see if someone else has a working/more mature redux + autobahn solution, if not let me know and I can work on this some more if it helps you. Good luck!

**Comment by mstumberger** [comment]
Hey, I really appreciate your quick reply.

I'd like that, it would helped me a lot and save a bunch of time since my plan was to use sagas like I found one boilerplate with another websocket library (without RPC and I'd really like that feature).

If it's in your interest I'd like contribute to this project.
If you provide example that you have I'm willing to write a complete example (like crossbar.io examples).

Regards,
Marko

**Comment by mstumberger** [comment]
Hey,
I got connection (yeey) :)
I didn't know how to connect to session

This is what I have so far:

```
import React from 'react';
import { render }  from 'react-dom';
import { createStore } from 'redux';
import { Provider } from 'react-redux'
import App from './App/App';
import autobahn, {Connection} from 'autobahn'
import createMiddleware from './redux-autobahn-middleware/middleware'

var connection = new Connection({url: 'ws://127.0.0.1:8080/ws', realm: 'realm1'});
console.log("Ok, AutobahnJS loaded", autobahn.version);

connection.open();

connection.onopen = (session) => {
    console.log("on OPEN");
    // ReactDOM.render(<App />, document.getElementById('root'));
    // 3. create the middleware
    const autobahnMiddleware = createMiddleware(session);
    // let testApp = combineReducers(reducers);
    const store = createStore(autobahnMiddleware);
};

connection.onclose = function (reason) {
    console.log("Connection lost: " + reason);
};

render( <App />, document.getElementById('root'));
```

**Comment by brycedarling** [comment]
Excellent! :) I just pushed up the part that I got working with connect and subscribe using poloniex:

https://github.com/brycedarling/poloniex-ticker

The most interesting thing to take a look at is probably `src/components/Ticker.jsx`

Edit: also take a look at https://github.com/brycedarling/poloniex-ticker/blob/master/src/configureStore.js as it does similar things to what you are doing above

**Comment by mstumberger** [comment]
Thank you very much. I really appreciate it!

**Comment by mstumberger** [comment]
Hello,

I got it working, i can subscribe and receive message, call RPC and receive response :)

> I got connect and subscribe calls working, but no events coming through... and I am not sure if it's something on my end or if the Poloniex push API isn't pushing events.. hmm.

I can confirm that this middleware works with my local server (used  [THIS](https://github.com/crossbario/crossbar-examples/tree/master/hello/python) backend)

**Comment by brycedarling** [comment]
Awwww yeahhh!! That's awesome!! Nice work Marko :D
