### ISSUE TITLE
Issue with managing opened connection

### ISSUE THREAD

**Issue by mstumberger** [brycedarling/redux-autobahn-js#16]
Hello,

I have created an [example](https://github.com/mstumberger/ReactReduxAutobahn_boilerplate) (check /app/containers/Login/) which is a template for my project and found out an interesting bug.

![middleware bug](https://user-images.githubusercontent.com/17837422/42500666-3252b570-8432-11e8-9832-3ea9fea7e523.png)

also when server gets offline and connection is reconnecting with it's mechanism once is connected again I can't close connection and i don't get subscribed to topics.

![middleware bug 2](https://user-images.githubusercontent.com/17837422/42500848-9af1c058-8432-11e8-91b6-218588c1123e.png)

Test server is:
url: `wss://cryptocademy.pro/ws`

Credentials:
username: `test`
passwd: `123pass4me`

**Comment by nijuyr** [comment]
I see there is a nasty bug in `setConnection`

```javascript
  autobahnMiddleware.setConnection = (newConnection) => {
    assert(
      newConnection &&
        typeof newConnection.open === 'function' &&
        typeof newConnection.close === 'function',
      'autobahn.Connection required',
    );

    if (autobahnMiddleware._connection) {
      // close the existing connection
      autobahnMiddleware.closeConnection('newConnection', 'new connection has been set');
    }

    newConnection.onopen = (s) => {
      autobahnMiddleware._dispatch(connectionOpened(newConnection));
    };

    newConnection.onclose = (reason, details) => {
      autobahnMiddleware._connection = null;
      autobahnMiddleware._dispatch(connectionClosed(reason, details));
    };

    autobahnMiddleware._connection = newConnection;
  };
```
when you try to set connection when there already is a connection (your second connection was set without closing the previous connection), 
```javascript
    newConnection.onclose = (reason, details) => {
      autobahnMiddleware._connection = null;
```
this part will set autobahnMiddleware._connection to null which is pointing at the new connection.

I guess the fix would be either
1. do not set _connection to null in `connection.onclose` but in `autobahnMIddleware.closeConnection`
2. reject `setConnection` if connection is already established

below is a snippet of middleware.js for fix 1

```javascript

export default function autobahnMiddlewareFactory({ connection } = {}) {
  function autobahnMiddleware({ dispatch }) {
    autobahnMiddleware._dispatch = dispatch;
    if (connection) {
      autobahnMiddleware.setConnection(connection);
      connection.open();
    }

    return next => (action) => {
      handleAction(autobahnMiddleware._connection, dispatch, next, action);
    };
  }

  /**
   * Sets the passed connection for the middleware that dispatches opened and closed connection actions and handles actions
   * @function setConnection
   * @memberof redux-autobahn:middleware
   * @param  {Connection} newConnection  the connection object
   */
  autobahnMiddleware.setConnection = (newConnection) => {
    assert(
      newConnection &&
        typeof newConnection.open === 'function' &&
        typeof newConnection.close === 'function',
      'autobahn.Connection required',
    );

    if (autobahnMiddleware._connection) {
      // close the existing connection
      autobahnMiddleware.closeConnection('newConnection', 'new connection has been set');
    }

    newConnection.onopen = (s) => {
      autobahnMiddleware._dispatch(connectionOpened(newConnection));
    };

    newConnection.onclose = (reason, details) => {
      autobahnMiddleware._dispatch(connectionClosed(reason, details));
    };

    autobahnMiddleware._connection = newConnection;
  };

  /**
   * Closes the current autobahn connection
   * @function closeConnection
   * @memberof redux-autobahn:middleware
   * @param  {string} reason  (optional) a WAMP URI providing a closing reason to the server side (e.g. 'com.myapp.close.signout'). default is `wamp.goodbye.normal`
   * @param  {string} message  human-readable closing message
   */
  autobahnMiddleware.closeConnection = (reason, message) => {
    if (isConnected(autobahnMiddleware._connection)) {
      autobahnMiddleware._connection.close(reason, message);
    }
    autobahnMiddleware._connection = null;
  };

  return autobahnMiddleware;
}
```

**Comment by brycedarling** [comment]
@nijuyr you're like my favorite person right now :) again, thank you so much for helping with these issues. If the fix for #1 works, it seems easier for people using the lib rather than handling an error with `setConnection` and managing it themselves. @mstumberger maybe you could test this change out and then y'all can send me a PR if it works? Thanks!

**Comment by mstumberger** [comment]
@nijuyr: Thank you for a solution! Will test it first thing in the morning.
@brycedarling: Definitely :)

**Comment by mstumberger** [comment]
I could not wait.
@nijuyr: Your solution solves both of the issues! Thank you!
Hope that nothing else pops up :)

**Comment by nijuyr** [comment]
@mstumberger thanks for confirming! glad you caught the bug :)

**Comment by mstumberger** [comment]
@nijuyr thank you for your quick intervention :)
Closing
