### ISSUE TITLE
RPC results cannot be retrieved per call

### ISSUE THREAD

**Issue by till-eugeneyu** [brycedarling/redux-autobahn-js#2]
Hi there,
thanks for writing this very useful middleware.

Here's things that I'm struggling to get through.

1. Authentication
as the middleware requires `connection` at the begging of its creation, auth with user/password input can't be inserted once it's initialised.
Tho I have this workaround but not sure if it's a clean approach
```
let connection = null;
let session = null;
let _dispatch = null;

export const setConnection = (conn) => {
  connection = conn;

  /* eslint-disable no-param-reassign */
  connection.onopen = (s) => {
    session = s;

    _dispatch(connectionOpened(session));
  };

  connection.onclose = () => {
    session = null;

    _dispatch(connectionClosed());
  };
};
```
basically I just exposed `setConnection` function which sets the connection object.

2. RPC cannot be retrieved accordingly per call.
Since all results for RPC come as `RESULT` action, I have no reference that which reducer should handle which RESULT.
E.g., if `uri_1` call and `uri_2` were called one after another, both will come as `RESULT`.
dispatch(callAction(uri_1)) -> RESULT
dispatch(callAction(uri_2)) -> RESULT
when it arrives in reducers, how should it handle the results when it doesn't know which RPC uri called it?

I also have a workaround for this by passing actions that will be called when the response/error arrives.
- action creator
```
export const call = (procedure, args, kwargs, options, resultAction, errorAction) => ({
  type: types.CALL,
  procedure,
  args,
  kwargs,
  options,
  resultAction,
  errorAction
});
```
- middleware.js
```
    case types.CALL:
      return !isConnected(session) ? dispatch(disconnected())
        : session.call(action.procedure, action.args, action.kwargs, action.options).then((res) => {
          if (action.resultAction) {
            return dispatch(action.resultAction(res));
          }
          return dispatch(result(res));
        }, (err) => {
          if (action.errorAction) {
            return dispatch(action.errorAction(err));
          }
          return dispatch(callError(err));
        });
```
so it will dispatch the passed `resultAction` and `errorAction` accordingly if they were passed to the call action.

I'm banging my head against to this redux-middleware thing (not your library but generally) and yet to know what the neat approach is.

Please shed some light. Thanks!

**Comment by brycedarling** [comment]
Well, I hacked this thing together in like 2 or 3 sessions to serve my purposes and so there are most definitely going to be rough edges... and it looks like you've found some :) it was also half a year ago so now this code is almost as foreign to me as it is to you, hah!

Your solutions look fine to me, especially if they are working for you then I would consider it good enough. Another approach might be if we could get the URI that was passed to the action back out in the result, then you could compare URI's for a match, but I don't really think this would be necessarily better or cleaner.. just different.

**Comment by till-eugeneyu** [comment]
@brycedarling Thanks for the quick reply. cool I understand how it was raised.

yeah both workarounds work as it is. I guess passing a URI could work but it won't cover the case where two calls to the same URI were called but with different parameters.

It is good for now tho I might find some more edges later on, I'll perhaps make a PR if you'd like to maintain this repo.
 
Cheers!

**Comment by brycedarling** [comment]
> I guess passing a URI could work but it won't cover the case where two calls to the same URI were called but with different parameters.

Yeah, good point. What you have is certainly superior in that regard.

If you wanna make a PR go for it, might help someone else that stumbles upon it! :)

**Comment by mstumberger** [comment]
Hey @till-eugeneyu,

try this in middleware.js:

```
  var result = function result(procedure, args, kwargs, results, options) {
    return {
      type: types.RESULT,
      procedure,
      args,
      kwargs,
      results,
      options,
    };
  };
```

     case types.CALL:
      return !isConnected(session) ? dispatch(disconnected())
        : session.call(action.procedure, action.args, action.kwargs, action.options).then((res) => {
          return dispatch(result(action.procedure, action.args, action.kwargs, res, action.options));
        }, (err) => {
          return dispatch(callError(err));
        });

**Comment by brycedarling** [comment]
Hey @till-eugeneyu any chance you still have your setConnection solution around and could submit a PR for it? It would be helpful to other people running in to the same problem you did, thanks!

**Comment by nijuyr** [comment]
@brycedarling this is `till-eugeneyu`. I've just created the PR. understand it's not the cleanest approach but just what I did up there. cheers.

**Comment by nijuyr** [comment]
@brycedarling I've also created a PR for the other issue as well. all the best.
