### ISSUE TITLE
Put it on NPM

### ISSUE THREAD

**Issue by jesper-bylund** [brycedarling/redux-autobahn-js#3]
Not really an issue, would just save a lot of time. :)

**Comment by brycedarling** [comment]
Yeah, you are right, that would be a good idea. When I first wrote it, I didn't really expect anyone else to use it tbh but a few people have been. Better documentation with example usage would probably be good to add too. Thanks for the suggestion Jesper!

**Comment by jesper-bylund** [comment]
It's about to blow up I'd think. Didn't find any other libs that worked. :)
